server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://116.62.119.190:33306/readercenter
    driver-class-name: com.mysql.jdbc.Driver
    username: bi110
    password: lgsc123
    #url: jdbc:mysql://127.0.0.1:3306/spring_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #driver-class-name: com.mysql.jdbc.Driver
    #username: root
    #password: Cpic1234
    servlet:
      multipart:
        #      最大文件大小。值可以使用后缀“MB”或“KB”。指示兆字节或千字节大小。
        max-file-size: 20MB
        #         # 最大请求大小可以是mb也可以是kb
        max-request-size: 200MB
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.feng.su.entity

